language: node_js
node_js:
  - '10'

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

cache:
  yarn: true
  directories:
    - "node_modules"

# before_script:
#   - yarn run lerna run prepublish

install:
  - yarn global add lerna jest
  - lerna bootstrap

matrix:
  include:
    - name: "UI"
      env: PACKAGE_LOCATION=ui
  
script: 
  - cd $PACKAGE_LOCATION
  - yarn test

# before_deploy:
#   - git config --global user.email ${GITHUB_EMAIL}
#   - git config --global user.name ${GITHUB_USER}
#   - git remote set-url origin "https://${GITHUB_TOKEN}@github.com/YOUR/PROJECT.git" > /dev/null 2>&1
#   - git checkout release
#   - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
# deploy:
#   provider: script
#   script: "yarn run lerna:publish"
#   skip_cleanup: true
#   on:
#     node: "10"
#     branch: release